
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rtd_rails_api_development

  
test:
  <<: *default
  database: rtd_rails_api_test


production:
  <<: *default
  database: rtd_rails_api_production
  username: rtd_rails_api
  password: <%= ENV['RTD_RAILS_API_DATABASE_PASSWORD'] %>


# default: &default  
#   adapter: postgresql  
#   encoding: unicode  
#   username: postgres  
#   password:  
#   pool: 5  
#   host: db 
# production:  
#   <<: *default  
#   database: default