:schedule:
  delete_all_favorite_possible_routes:
    cron: '0 0 * * 6'
    class: DeleteAllFavoritePossibleRoutes

  delete_expiring_possible_routes:
    cron: '5 0 * * 0-6'
    class: DeleteExpiringPossibleRoutes
